[package]
name = "roil"
version = "0.6.2"
edition = "2024"
authors = ["lizelit <lizelit.you@gmail.com>"]
description = "A TUI-based directory editor"
license = "MIT"
repository = "https://github.com/lizelit/roil"
readme = "README.md"
keywords = ["tui", "directory", "editor"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.100"
crossterm = "0.27.0"
natord = "1.0.9"
ratatui = "0.26"
ratatui-textarea = "0.4.1"
unicode-width = "0.2.2"
